nohup: ignoring input
Traceback (most recent call last):
  File "analysis.py", line 101, in <module>
    SVCCA(args.data_dir1, args.data_dir2, args.svd_dim)
  File "analysis.py", line 15, in SVCCA
    acts1 = np.load(file1)
  File "/disk/ocean/zheng/miniconda3/envs/cdt/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/disk/ocean/zheng/summarization_svcca/out/activations/amazon_reviews/seed1/100_data/top5/epoch111/Movies_and_TV_layer_0_hidden_state.npy'
Traceback (most recent call last):
  File "analysis.py", line 101, in <module>
    SVCCA(args.data_dir1, args.data_dir2, args.svd_dim)
  File "analysis.py", line 15, in SVCCA
    acts1 = np.load(file1)
  File "/disk/ocean/zheng/miniconda3/envs/cdt/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/disk/ocean/zheng/summarization_svcca/out/activations/amazon_reviews/seed1/100_data/top5/epoch121/Movies_and_TV_layer_0_hidden_state.npy'
Traceback (most recent call last):
  File "analysis.py", line 101, in <module>
    SVCCA(args.data_dir1, args.data_dir2, args.svd_dim)
  File "analysis.py", line 15, in SVCCA
    acts1 = np.load(file1)
  File "/disk/ocean/zheng/miniconda3/envs/cdt/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/disk/ocean/zheng/summarization_svcca/out/activations/amazon_reviews/seed1/100_data/top5/epoch141/Movies_and_TV_layer_0_hidden_state.npy'
Traceback (most recent call last):
  File "analysis.py", line 101, in <module>
    SVCCA(args.data_dir1, args.data_dir2, args.svd_dim)
  File "analysis.py", line 15, in SVCCA
    acts1 = np.load(file1)
  File "/disk/ocean/zheng/miniconda3/envs/cdt/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/disk/ocean/zheng/summarization_svcca/out/activations/amazon_reviews/seed1/100_data/top5/epoch151/Movies_and_TV_layer_0_hidden_state.npy'
Traceback (most recent call last):
  File "analysis.py", line 101, in <module>
    SVCCA(args.data_dir1, args.data_dir2, args.svd_dim)
  File "analysis.py", line 15, in SVCCA
    acts1 = np.load(file1)
  File "/disk/ocean/zheng/miniconda3/envs/cdt/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/disk/ocean/zheng/summarization_svcca/out/activations/amazon_reviews/seed1/100_data/top5/epoch161/Movies_and_TV_layer_0_hidden_state.npy'
Traceback (most recent call last):
  File "analysis.py", line 101, in <module>
    SVCCA(args.data_dir1, args.data_dir2, args.svd_dim)
  File "analysis.py", line 15, in SVCCA
    acts1 = np.load(file1)
  File "/disk/ocean/zheng/miniconda3/envs/cdt/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/disk/ocean/zheng/summarization_svcca/out/activations/amazon_reviews/seed1/100_data/top5/epoch171/Movies_and_TV_layer_0_hidden_state.npy'
Traceback (most recent call last):
  File "analysis.py", line 101, in <module>
    SVCCA(args.data_dir1, args.data_dir2, args.svd_dim)
  File "analysis.py", line 15, in SVCCA
    acts1 = np.load(file1)
  File "/disk/ocean/zheng/miniconda3/envs/cdt/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/disk/ocean/zheng/summarization_svcca/out/activations/amazon_reviews/seed1/100_data/top5/epoch181/Movies_and_TV_layer_0_hidden_state.npy'
Traceback (most recent call last):
  File "analysis.py", line 101, in <module>
    SVCCA(args.data_dir1, args.data_dir2, args.svd_dim)
  File "analysis.py", line 15, in SVCCA
    acts1 = np.load(file1)
  File "/disk/ocean/zheng/miniconda3/envs/cdt/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/disk/ocean/zheng/summarization_svcca/out/activations/amazon_reviews/seed1/100_data/top5/epoch191/Movies_and_TV_layer_0_hidden_state.npy'
Traceback (most recent call last):
  File "analysis.py", line 101, in <module>
    SVCCA(args.data_dir1, args.data_dir2, args.svd_dim)
  File "analysis.py", line 15, in SVCCA
    acts1 = np.load(file1)
  File "/disk/ocean/zheng/miniconda3/envs/cdt/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/disk/ocean/zheng/summarization_svcca/out/activations/amazon_reviews/seed1/100_data/top5/epoch201/Movies_and_TV_layer_0_hidden_state.npy'
Traceback (most recent call last):
  File "analysis.py", line 101, in <module>
    SVCCA(args.data_dir1, args.data_dir2, args.svd_dim)
  File "analysis.py", line 16, in SVCCA
    acts2 = np.load(file2)
  File "/disk/ocean/zheng/miniconda3/envs/cdt/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/disk/ocean/zheng/summarization_svcca/out/activations/amazon_reviews/seed1/100_data/Movies_and_TV/epoch111/Movies_and_TV_layer_1_hidden_state.npy'
Traceback (most recent call last):
  File "analysis.py", line 101, in <module>
    SVCCA(args.data_dir1, args.data_dir2, args.svd_dim)
  File "analysis.py", line 15, in SVCCA
    acts1 = np.load(file1)
  File "/disk/ocean/zheng/miniconda3/envs/cdt/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/disk/ocean/zheng/summarization_svcca/out/activations/amazon_reviews/seed1/100_data/top5/epoch121/Movies_and_TV_layer_1_hidden_state.npy'
Traceback (most recent call last):
  File "analysis.py", line 101, in <module>
    SVCCA(args.data_dir1, args.data_dir2, args.svd_dim)
  File "analysis.py", line 15, in SVCCA
    acts1 = np.load(file1)
  File "/disk/ocean/zheng/miniconda3/envs/cdt/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/disk/ocean/zheng/summarization_svcca/out/activations/amazon_reviews/seed1/100_data/top5/epoch131/Movies_and_TV_layer_1_hidden_state.npy'
Traceback (most recent call last):
  File "analysis.py", line 101, in <module>
    SVCCA(args.data_dir1, args.data_dir2, args.svd_dim)
  File "analysis.py", line 15, in SVCCA
    acts1 = np.load(file1)
  File "/disk/ocean/zheng/miniconda3/envs/cdt/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/disk/ocean/zheng/summarization_svcca/out/activations/amazon_reviews/seed1/100_data/top5/epoch141/Movies_and_TV_layer_1_hidden_state.npy'
Traceback (most recent call last):
  File "analysis.py", line 101, in <module>
    SVCCA(args.data_dir1, args.data_dir2, args.svd_dim)
  File "analysis.py", line 15, in SVCCA
    acts1 = np.load(file1)
  File "/disk/ocean/zheng/miniconda3/envs/cdt/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/disk/ocean/zheng/summarization_svcca/out/activations/amazon_reviews/seed1/100_data/top5/epoch151/Movies_and_TV_layer_1_hidden_state.npy'
Traceback (most recent call last):
  File "analysis.py", line 101, in <module>
    SVCCA(args.data_dir1, args.data_dir2, args.svd_dim)
  File "analysis.py", line 15, in SVCCA
    acts1 = np.load(file1)
  File "/disk/ocean/zheng/miniconda3/envs/cdt/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/disk/ocean/zheng/summarization_svcca/out/activations/amazon_reviews/seed1/100_data/top5/epoch161/Movies_and_TV_layer_1_hidden_state.npy'
Traceback (most recent call last):
  File "analysis.py", line 101, in <module>
    SVCCA(args.data_dir1, args.data_dir2, args.svd_dim)
  File "analysis.py", line 15, in SVCCA
    acts1 = np.load(file1)
  File "/disk/ocean/zheng/miniconda3/envs/cdt/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/disk/ocean/zheng/summarization_svcca/out/activations/amazon_reviews/seed1/100_data/top5/epoch171/Movies_and_TV_layer_1_hidden_state.npy'
Traceback (most recent call last):
  File "analysis.py", line 101, in <module>
    SVCCA(args.data_dir1, args.data_dir2, args.svd_dim)
  File "analysis.py", line 15, in SVCCA
    acts1 = np.load(file1)
  File "/disk/ocean/zheng/miniconda3/envs/cdt/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/disk/ocean/zheng/summarization_svcca/out/activations/amazon_reviews/seed1/100_data/top5/epoch201/Movies_and_TV_layer_1_hidden_state.npy'
Traceback (most recent call last):
  File "analysis.py", line 101, in <module>
    SVCCA(args.data_dir1, args.data_dir2, args.svd_dim)
  File "analysis.py", line 15, in SVCCA
    acts1 = np.load(file1)
  File "/disk/ocean/zheng/miniconda3/envs/cdt/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/disk/ocean/zheng/summarization_svcca/out/activations/amazon_reviews/seed1/100_data/top5/epoch111/Movies_and_TV_layer_2_hidden_state.npy'
Traceback (most recent call last):
  File "analysis.py", line 101, in <module>
    SVCCA(args.data_dir1, args.data_dir2, args.svd_dim)
  File "analysis.py", line 15, in SVCCA
    acts1 = np.load(file1)
  File "/disk/ocean/zheng/miniconda3/envs/cdt/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/disk/ocean/zheng/summarization_svcca/out/activations/amazon_reviews/seed1/100_data/top5/epoch121/Movies_and_TV_layer_2_hidden_state.npy'
Traceback (most recent call last):
  File "analysis.py", line 101, in <module>
    SVCCA(args.data_dir1, args.data_dir2, args.svd_dim)
  File "analysis.py", line 15, in SVCCA
    acts1 = np.load(file1)
  File "/disk/ocean/zheng/miniconda3/envs/cdt/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/disk/ocean/zheng/summarization_svcca/out/activations/amazon_reviews/seed1/100_data/top5/epoch141/Movies_and_TV_layer_2_hidden_state.npy'
Traceback (most recent call last):
  File "analysis.py", line 101, in <module>
    SVCCA(args.data_dir1, args.data_dir2, args.svd_dim)
  File "analysis.py", line 15, in SVCCA
    acts1 = np.load(file1)
  File "/disk/ocean/zheng/miniconda3/envs/cdt/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/disk/ocean/zheng/summarization_svcca/out/activations/amazon_reviews/seed1/100_data/top5/epoch151/Movies_and_TV_layer_2_hidden_state.npy'
Traceback (most recent call last):
  File "analysis.py", line 101, in <module>
    SVCCA(args.data_dir1, args.data_dir2, args.svd_dim)
  File "analysis.py", line 15, in SVCCA
    acts1 = np.load(file1)
  File "/disk/ocean/zheng/miniconda3/envs/cdt/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/disk/ocean/zheng/summarization_svcca/out/activations/amazon_reviews/seed1/100_data/top5/epoch161/Movies_and_TV_layer_2_hidden_state.npy'
Traceback (most recent call last):
  File "analysis.py", line 101, in <module>
    SVCCA(args.data_dir1, args.data_dir2, args.svd_dim)
  File "analysis.py", line 15, in SVCCA
    acts1 = np.load(file1)
  File "/disk/ocean/zheng/miniconda3/envs/cdt/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/disk/ocean/zheng/summarization_svcca/out/activations/amazon_reviews/seed1/100_data/top5/epoch171/Movies_and_TV_layer_2_hidden_state.npy'
Traceback (most recent call last):
  File "analysis.py", line 101, in <module>
    SVCCA(args.data_dir1, args.data_dir2, args.svd_dim)
  File "analysis.py", line 15, in SVCCA
    acts1 = np.load(file1)
  File "/disk/ocean/zheng/miniconda3/envs/cdt/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/disk/ocean/zheng/summarization_svcca/out/activations/amazon_reviews/seed1/100_data/top5/epoch181/Movies_and_TV_layer_2_hidden_state.npy'
Traceback (most recent call last):
  File "analysis.py", line 101, in <module>
    SVCCA(args.data_dir1, args.data_dir2, args.svd_dim)
  File "analysis.py", line 15, in SVCCA
    acts1 = np.load(file1)
  File "/disk/ocean/zheng/miniconda3/envs/cdt/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/disk/ocean/zheng/summarization_svcca/out/activations/amazon_reviews/seed1/100_data/top5/epoch191/Movies_and_TV_layer_2_hidden_state.npy'
Traceback (most recent call last):
  File "analysis.py", line 101, in <module>
    SVCCA(args.data_dir1, args.data_dir2, args.svd_dim)
  File "analysis.py", line 15, in SVCCA
    acts1 = np.load(file1)
  File "/disk/ocean/zheng/miniconda3/envs/cdt/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/disk/ocean/zheng/summarization_svcca/out/activations/amazon_reviews/seed1/100_data/top5/epoch201/Movies_and_TV_layer_2_hidden_state.npy'
Traceback (most recent call last):
  File "analysis.py", line 101, in <module>
    SVCCA(args.data_dir1, args.data_dir2, args.svd_dim)
  File "analysis.py", line 15, in SVCCA
    acts1 = np.load(file1)
  File "/disk/ocean/zheng/miniconda3/envs/cdt/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/disk/ocean/zheng/summarization_svcca/out/activations/amazon_reviews/seed1/100_data/top5/epoch111/Movies_and_TV_layer_3_hidden_state.npy'
Traceback (most recent call last):
  File "analysis.py", line 101, in <module>
    SVCCA(args.data_dir1, args.data_dir2, args.svd_dim)
  File "analysis.py", line 16, in SVCCA
    acts2 = np.load(file2)
  File "/disk/ocean/zheng/miniconda3/envs/cdt/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/disk/ocean/zheng/summarization_svcca/out/activations/amazon_reviews/seed1/100_data/Movies_and_TV/epoch121/Movies_and_TV_layer_3_hidden_state.npy'
Traceback (most recent call last):
  File "analysis.py", line 101, in <module>
    SVCCA(args.data_dir1, args.data_dir2, args.svd_dim)
  File "analysis.py", line 16, in SVCCA
    acts2 = np.load(file2)
  File "/disk/ocean/zheng/miniconda3/envs/cdt/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/disk/ocean/zheng/summarization_svcca/out/activations/amazon_reviews/seed1/100_data/Movies_and_TV/epoch131/Movies_and_TV_layer_3_hidden_state.npy'
Traceback (most recent call last):
  File "analysis.py", line 101, in <module>
    SVCCA(args.data_dir1, args.data_dir2, args.svd_dim)
  File "analysis.py", line 15, in SVCCA
    acts1 = np.load(file1)
  File "/disk/ocean/zheng/miniconda3/envs/cdt/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/disk/ocean/zheng/summarization_svcca/out/activations/amazon_reviews/seed1/100_data/top5/epoch141/Movies_and_TV_layer_3_hidden_state.npy'
Traceback (most recent call last):
  File "analysis.py", line 101, in <module>
    SVCCA(args.data_dir1, args.data_dir2, args.svd_dim)
  File "analysis.py", line 15, in SVCCA
    acts1 = np.load(file1)
  File "/disk/ocean/zheng/miniconda3/envs/cdt/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/disk/ocean/zheng/summarization_svcca/out/activations/amazon_reviews/seed1/100_data/top5/epoch151/Movies_and_TV_layer_3_hidden_state.npy'
Traceback (most recent call last):
  File "analysis.py", line 101, in <module>
    SVCCA(args.data_dir1, args.data_dir2, args.svd_dim)
  File "analysis.py", line 15, in SVCCA
    acts1 = np.load(file1)
  File "/disk/ocean/zheng/miniconda3/envs/cdt/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/disk/ocean/zheng/summarization_svcca/out/activations/amazon_reviews/seed1/100_data/top5/epoch171/Movies_and_TV_layer_3_hidden_state.npy'
Traceback (most recent call last):
  File "analysis.py", line 101, in <module>
    SVCCA(args.data_dir1, args.data_dir2, args.svd_dim)
  File "analysis.py", line 15, in SVCCA
    acts1 = np.load(file1)
  File "/disk/ocean/zheng/miniconda3/envs/cdt/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/disk/ocean/zheng/summarization_svcca/out/activations/amazon_reviews/seed1/100_data/top5/epoch181/Movies_and_TV_layer_3_hidden_state.npy'
Traceback (most recent call last):
  File "analysis.py", line 101, in <module>
    SVCCA(args.data_dir1, args.data_dir2, args.svd_dim)
  File "analysis.py", line 15, in SVCCA
    acts1 = np.load(file1)
  File "/disk/ocean/zheng/miniconda3/envs/cdt/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/disk/ocean/zheng/summarization_svcca/out/activations/amazon_reviews/seed1/100_data/top5/epoch191/Movies_and_TV_layer_3_hidden_state.npy'
Traceback (most recent call last):
  File "analysis.py", line 101, in <module>
    SVCCA(args.data_dir1, args.data_dir2, args.svd_dim)
  File "analysis.py", line 15, in SVCCA
    acts1 = np.load(file1)
  File "/disk/ocean/zheng/miniconda3/envs/cdt/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/disk/ocean/zheng/summarization_svcca/out/activations/amazon_reviews/seed1/100_data/top5/epoch121/Movies_and_TV_layer_4_hidden_state.npy'
Traceback (most recent call last):
  File "analysis.py", line 101, in <module>
    SVCCA(args.data_dir1, args.data_dir2, args.svd_dim)
  File "analysis.py", line 15, in SVCCA
    acts1 = np.load(file1)
  File "/disk/ocean/zheng/miniconda3/envs/cdt/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/disk/ocean/zheng/summarization_svcca/out/activations/amazon_reviews/seed1/100_data/top5/epoch131/Movies_and_TV_layer_4_hidden_state.npy'
Traceback (most recent call last):
  File "analysis.py", line 101, in <module>
    SVCCA(args.data_dir1, args.data_dir2, args.svd_dim)
  File "analysis.py", line 15, in SVCCA
    acts1 = np.load(file1)
  File "/disk/ocean/zheng/miniconda3/envs/cdt/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/disk/ocean/zheng/summarization_svcca/out/activations/amazon_reviews/seed1/100_data/top5/epoch141/Movies_and_TV_layer_4_hidden_state.npy'
Traceback (most recent call last):
  File "analysis.py", line 101, in <module>
    SVCCA(args.data_dir1, args.data_dir2, args.svd_dim)
  File "analysis.py", line 15, in SVCCA
    acts1 = np.load(file1)
  File "/disk/ocean/zheng/miniconda3/envs/cdt/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/disk/ocean/zheng/summarization_svcca/out/activations/amazon_reviews/seed1/100_data/top5/epoch151/Movies_and_TV_layer_4_hidden_state.npy'
Traceback (most recent call last):
  File "analysis.py", line 101, in <module>
    SVCCA(args.data_dir1, args.data_dir2, args.svd_dim)
  File "analysis.py", line 15, in SVCCA
    acts1 = np.load(file1)
  File "/disk/ocean/zheng/miniconda3/envs/cdt/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/disk/ocean/zheng/summarization_svcca/out/activations/amazon_reviews/seed1/100_data/top5/epoch161/Movies_and_TV_layer_4_hidden_state.npy'
Traceback (most recent call last):
  File "analysis.py", line 101, in <module>
    SVCCA(args.data_dir1, args.data_dir2, args.svd_dim)
  File "analysis.py", line 15, in SVCCA
    acts1 = np.load(file1)
  File "/disk/ocean/zheng/miniconda3/envs/cdt/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/disk/ocean/zheng/summarization_svcca/out/activations/amazon_reviews/seed1/100_data/top5/epoch171/Movies_and_TV_layer_4_hidden_state.npy'
Traceback (most recent call last):
  File "analysis.py", line 101, in <module>
    SVCCA(args.data_dir1, args.data_dir2, args.svd_dim)
  File "analysis.py", line 16, in SVCCA
    acts2 = np.load(file2)
  File "/disk/ocean/zheng/miniconda3/envs/cdt/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/disk/ocean/zheng/summarization_svcca/out/activations/amazon_reviews/seed1/100_data/Movies_and_TV/epoch181/Movies_and_TV_layer_4_hidden_state.npy'
Traceback (most recent call last):
  File "analysis.py", line 101, in <module>
    SVCCA(args.data_dir1, args.data_dir2, args.svd_dim)
  File "analysis.py", line 15, in SVCCA
    acts1 = np.load(file1)
  File "/disk/ocean/zheng/miniconda3/envs/cdt/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/disk/ocean/zheng/summarization_svcca/out/activations/amazon_reviews/seed1/100_data/top5/epoch191/Movies_and_TV_layer_4_hidden_state.npy'
Traceback (most recent call last):
  File "analysis.py", line 101, in <module>
    SVCCA(args.data_dir1, args.data_dir2, args.svd_dim)
  File "analysis.py", line 15, in SVCCA
    acts1 = np.load(file1)
  File "/disk/ocean/zheng/miniconda3/envs/cdt/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/disk/ocean/zheng/summarization_svcca/out/activations/amazon_reviews/seed1/100_data/top5/epoch201/Movies_and_TV_layer_4_hidden_state.npy'
Traceback (most recent call last):
  File "analysis.py", line 101, in <module>
    SVCCA(args.data_dir1, args.data_dir2, args.svd_dim)
  File "analysis.py", line 15, in SVCCA
    acts1 = np.load(file1)
  File "/disk/ocean/zheng/miniconda3/envs/cdt/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/disk/ocean/zheng/summarization_svcca/out/activations/amazon_reviews/seed1/100_data/top5/epoch131/Movies_and_TV_layer_5_hidden_state.npy'
Traceback (most recent call last):
  File "analysis.py", line 101, in <module>
    SVCCA(args.data_dir1, args.data_dir2, args.svd_dim)
  File "analysis.py", line 15, in SVCCA
    acts1 = np.load(file1)
  File "/disk/ocean/zheng/miniconda3/envs/cdt/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/disk/ocean/zheng/summarization_svcca/out/activations/amazon_reviews/seed1/100_data/top5/epoch151/Movies_and_TV_layer_5_hidden_state.npy'
Traceback (most recent call last):
  File "analysis.py", line 101, in <module>
    SVCCA(args.data_dir1, args.data_dir2, args.svd_dim)
  File "analysis.py", line 15, in SVCCA
    acts1 = np.load(file1)
  File "/disk/ocean/zheng/miniconda3/envs/cdt/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/disk/ocean/zheng/summarization_svcca/out/activations/amazon_reviews/seed1/100_data/top5/epoch161/Movies_and_TV_layer_5_hidden_state.npy'
Traceback (most recent call last):
  File "analysis.py", line 101, in <module>
    SVCCA(args.data_dir1, args.data_dir2, args.svd_dim)
  File "analysis.py", line 16, in SVCCA
    acts2 = np.load(file2)
  File "/disk/ocean/zheng/miniconda3/envs/cdt/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/disk/ocean/zheng/summarization_svcca/out/activations/amazon_reviews/seed1/100_data/Movies_and_TV/epoch171/Movies_and_TV_layer_5_hidden_state.npy'
Traceback (most recent call last):
  File "analysis.py", line 101, in <module>
    SVCCA(args.data_dir1, args.data_dir2, args.svd_dim)
  File "analysis.py", line 15, in SVCCA
    acts1 = np.load(file1)
  File "/disk/ocean/zheng/miniconda3/envs/cdt/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/disk/ocean/zheng/summarization_svcca/out/activations/amazon_reviews/seed1/100_data/top5/epoch181/Movies_and_TV_layer_5_hidden_state.npy'
Traceback (most recent call last):
  File "analysis.py", line 101, in <module>
    SVCCA(args.data_dir1, args.data_dir2, args.svd_dim)
  File "analysis.py", line 15, in SVCCA
    acts1 = np.load(file1)
  File "/disk/ocean/zheng/miniconda3/envs/cdt/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/disk/ocean/zheng/summarization_svcca/out/activations/amazon_reviews/seed1/100_data/top5/epoch191/Movies_and_TV_layer_5_hidden_state.npy'
Traceback (most recent call last):
  File "analysis.py", line 101, in <module>
    SVCCA(args.data_dir1, args.data_dir2, args.svd_dim)
  File "analysis.py", line 15, in SVCCA
    acts1 = np.load(file1)
  File "/disk/ocean/zheng/miniconda3/envs/cdt/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/disk/ocean/zheng/summarization_svcca/out/activations/amazon_reviews/seed1/100_data/top5/epoch201/Movies_and_TV_layer_5_hidden_state.npy'
Traceback (most recent call last):
  File "analysis.py", line 101, in <module>
    SVCCA(args.data_dir1, args.data_dir2, args.svd_dim)
  File "analysis.py", line 16, in SVCCA
    acts2 = np.load(file2)
  File "/disk/ocean/zheng/miniconda3/envs/cdt/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/disk/ocean/zheng/summarization_svcca/out/activations/amazon_reviews/seed1/100_data/Movies_and_TV/epoch121/Movies_and_TV_layer_6_hidden_state.npy'
Traceback (most recent call last):
  File "analysis.py", line 101, in <module>
    SVCCA(args.data_dir1, args.data_dir2, args.svd_dim)
  File "analysis.py", line 15, in SVCCA
    acts1 = np.load(file1)
  File "/disk/ocean/zheng/miniconda3/envs/cdt/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/disk/ocean/zheng/summarization_svcca/out/activations/amazon_reviews/seed1/100_data/top5/epoch131/Movies_and_TV_layer_6_hidden_state.npy'
Traceback (most recent call last):
  File "analysis.py", line 101, in <module>
    SVCCA(args.data_dir1, args.data_dir2, args.svd_dim)
  File "analysis.py", line 15, in SVCCA
    acts1 = np.load(file1)
  File "/disk/ocean/zheng/miniconda3/envs/cdt/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/disk/ocean/zheng/summarization_svcca/out/activations/amazon_reviews/seed1/100_data/top5/epoch141/Movies_and_TV_layer_6_hidden_state.npy'
Traceback (most recent call last):
  File "analysis.py", line 101, in <module>
    SVCCA(args.data_dir1, args.data_dir2, args.svd_dim)
  File "analysis.py", line 15, in SVCCA
    acts1 = np.load(file1)
  File "/disk/ocean/zheng/miniconda3/envs/cdt/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/disk/ocean/zheng/summarization_svcca/out/activations/amazon_reviews/seed1/100_data/top5/epoch151/Movies_and_TV_layer_6_hidden_state.npy'
Traceback (most recent call last):
  File "analysis.py", line 101, in <module>
    SVCCA(args.data_dir1, args.data_dir2, args.svd_dim)
  File "analysis.py", line 15, in SVCCA
    acts1 = np.load(file1)
  File "/disk/ocean/zheng/miniconda3/envs/cdt/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/disk/ocean/zheng/summarization_svcca/out/activations/amazon_reviews/seed1/100_data/top5/epoch161/Movies_and_TV_layer_6_hidden_state.npy'
Traceback (most recent call last):
  File "analysis.py", line 101, in <module>
    SVCCA(args.data_dir1, args.data_dir2, args.svd_dim)
  File "analysis.py", line 15, in SVCCA
    acts1 = np.load(file1)
  File "/disk/ocean/zheng/miniconda3/envs/cdt/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/disk/ocean/zheng/summarization_svcca/out/activations/amazon_reviews/seed1/100_data/top5/epoch171/Movies_and_TV_layer_6_hidden_state.npy'
Traceback (most recent call last):
  File "analysis.py", line 101, in <module>
    SVCCA(args.data_dir1, args.data_dir2, args.svd_dim)
  File "analysis.py", line 15, in SVCCA
    acts1 = np.load(file1)
  File "/disk/ocean/zheng/miniconda3/envs/cdt/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/disk/ocean/zheng/summarization_svcca/out/activations/amazon_reviews/seed1/100_data/top5/epoch181/Movies_and_TV_layer_6_hidden_state.npy'
Traceback (most recent call last):
  File "analysis.py", line 101, in <module>
    SVCCA(args.data_dir1, args.data_dir2, args.svd_dim)
  File "analysis.py", line 15, in SVCCA
    acts1 = np.load(file1)
  File "/disk/ocean/zheng/miniconda3/envs/cdt/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/disk/ocean/zheng/summarization_svcca/out/activations/amazon_reviews/seed1/100_data/top5/epoch201/Movies_and_TV_layer_6_hidden_state.npy'
Traceback (most recent call last):
  File "analysis.py", line 101, in <module>
    SVCCA(args.data_dir1, args.data_dir2, args.svd_dim)
  File "analysis.py", line 16, in SVCCA
    acts2 = np.load(file2)
  File "/disk/ocean/zheng/miniconda3/envs/cdt/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/disk/ocean/zheng/summarization_svcca/out/activations/amazon_reviews/seed1/100_data/Movies_and_TV/epoch111/Movies_and_TV_layer_7_hidden_state.npy'
Traceback (most recent call last):
  File "analysis.py", line 101, in <module>
    SVCCA(args.data_dir1, args.data_dir2, args.svd_dim)
  File "analysis.py", line 15, in SVCCA
    acts1 = np.load(file1)
  File "/disk/ocean/zheng/miniconda3/envs/cdt/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/disk/ocean/zheng/summarization_svcca/out/activations/amazon_reviews/seed1/100_data/top5/epoch121/Movies_and_TV_layer_7_hidden_state.npy'
Traceback (most recent call last):
  File "analysis.py", line 101, in <module>
    SVCCA(args.data_dir1, args.data_dir2, args.svd_dim)
  File "analysis.py", line 15, in SVCCA
    acts1 = np.load(file1)
  File "/disk/ocean/zheng/miniconda3/envs/cdt/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/disk/ocean/zheng/summarization_svcca/out/activations/amazon_reviews/seed1/100_data/top5/epoch131/Movies_and_TV_layer_7_hidden_state.npy'
Traceback (most recent call last):
  File "analysis.py", line 101, in <module>
    SVCCA(args.data_dir1, args.data_dir2, args.svd_dim)
  File "analysis.py", line 15, in SVCCA
    acts1 = np.load(file1)
  File "/disk/ocean/zheng/miniconda3/envs/cdt/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/disk/ocean/zheng/summarization_svcca/out/activations/amazon_reviews/seed1/100_data/top5/epoch141/Movies_and_TV_layer_7_hidden_state.npy'
Traceback (most recent call last):
  File "analysis.py", line 101, in <module>
    SVCCA(args.data_dir1, args.data_dir2, args.svd_dim)
  File "analysis.py", line 16, in SVCCA
    acts2 = np.load(file2)
  File "/disk/ocean/zheng/miniconda3/envs/cdt/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/disk/ocean/zheng/summarization_svcca/out/activations/amazon_reviews/seed1/100_data/Movies_and_TV/epoch151/Movies_and_TV_layer_7_hidden_state.npy'
Traceback (most recent call last):
  File "analysis.py", line 101, in <module>
    SVCCA(args.data_dir1, args.data_dir2, args.svd_dim)
  File "analysis.py", line 15, in SVCCA
    acts1 = np.load(file1)
  File "/disk/ocean/zheng/miniconda3/envs/cdt/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/disk/ocean/zheng/summarization_svcca/out/activations/amazon_reviews/seed1/100_data/top5/epoch161/Movies_and_TV_layer_7_hidden_state.npy'
Traceback (most recent call last):
  File "analysis.py", line 101, in <module>
    SVCCA(args.data_dir1, args.data_dir2, args.svd_dim)
  File "analysis.py", line 15, in SVCCA
    acts1 = np.load(file1)
  File "/disk/ocean/zheng/miniconda3/envs/cdt/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/disk/ocean/zheng/summarization_svcca/out/activations/amazon_reviews/seed1/100_data/top5/epoch171/Movies_and_TV_layer_7_hidden_state.npy'
Traceback (most recent call last):
  File "analysis.py", line 101, in <module>
    SVCCA(args.data_dir1, args.data_dir2, args.svd_dim)
  File "analysis.py", line 15, in SVCCA
    acts1 = np.load(file1)
  File "/disk/ocean/zheng/miniconda3/envs/cdt/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/disk/ocean/zheng/summarization_svcca/out/activations/amazon_reviews/seed1/100_data/top5/epoch191/Movies_and_TV_layer_7_hidden_state.npy'
Traceback (most recent call last):
  File "analysis.py", line 101, in <module>
    SVCCA(args.data_dir1, args.data_dir2, args.svd_dim)
  File "analysis.py", line 16, in SVCCA
    acts2 = np.load(file2)
  File "/disk/ocean/zheng/miniconda3/envs/cdt/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/disk/ocean/zheng/summarization_svcca/out/activations/amazon_reviews/seed1/100_data/Movies_and_TV/epoch201/Movies_and_TV_layer_7_hidden_state.npy'
Traceback (most recent call last):
  File "analysis.py", line 101, in <module>
    SVCCA(args.data_dir1, args.data_dir2, args.svd_dim)
  File "analysis.py", line 15, in SVCCA
    acts1 = np.load(file1)
  File "/disk/ocean/zheng/miniconda3/envs/cdt/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/disk/ocean/zheng/summarization_svcca/out/activations/amazon_reviews/seed1/100_data/top5/epoch121/Movies_and_TV_layer_8_hidden_state.npy'
Traceback (most recent call last):
  File "analysis.py", line 101, in <module>
    SVCCA(args.data_dir1, args.data_dir2, args.svd_dim)
  File "analysis.py", line 15, in SVCCA
    acts1 = np.load(file1)
  File "/disk/ocean/zheng/miniconda3/envs/cdt/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/disk/ocean/zheng/summarization_svcca/out/activations/amazon_reviews/seed1/100_data/top5/epoch131/Movies_and_TV_layer_8_hidden_state.npy'
Traceback (most recent call last):
  File "analysis.py", line 101, in <module>
    SVCCA(args.data_dir1, args.data_dir2, args.svd_dim)
  File "analysis.py", line 15, in SVCCA
    acts1 = np.load(file1)
  File "/disk/ocean/zheng/miniconda3/envs/cdt/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/disk/ocean/zheng/summarization_svcca/out/activations/amazon_reviews/seed1/100_data/top5/epoch141/Movies_and_TV_layer_8_hidden_state.npy'
Traceback (most recent call last):
  File "analysis.py", line 101, in <module>
    SVCCA(args.data_dir1, args.data_dir2, args.svd_dim)
  File "analysis.py", line 15, in SVCCA
    acts1 = np.load(file1)
  File "/disk/ocean/zheng/miniconda3/envs/cdt/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/disk/ocean/zheng/summarization_svcca/out/activations/amazon_reviews/seed1/100_data/top5/epoch161/Movies_and_TV_layer_8_hidden_state.npy'
Traceback (most recent call last):
  File "analysis.py", line 101, in <module>
    SVCCA(args.data_dir1, args.data_dir2, args.svd_dim)
  File "analysis.py", line 16, in SVCCA
    acts2 = np.load(file2)
  File "/disk/ocean/zheng/miniconda3/envs/cdt/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/disk/ocean/zheng/summarization_svcca/out/activations/amazon_reviews/seed1/100_data/Movies_and_TV/epoch171/Movies_and_TV_layer_8_hidden_state.npy'
Traceback (most recent call last):
  File "analysis.py", line 101, in <module>
    SVCCA(args.data_dir1, args.data_dir2, args.svd_dim)
  File "analysis.py", line 15, in SVCCA
    acts1 = np.load(file1)
  File "/disk/ocean/zheng/miniconda3/envs/cdt/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/disk/ocean/zheng/summarization_svcca/out/activations/amazon_reviews/seed1/100_data/top5/epoch181/Movies_and_TV_layer_8_hidden_state.npy'
Traceback (most recent call last):
  File "analysis.py", line 101, in <module>
    SVCCA(args.data_dir1, args.data_dir2, args.svd_dim)
  File "analysis.py", line 15, in SVCCA
    acts1 = np.load(file1)
  File "/disk/ocean/zheng/miniconda3/envs/cdt/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/disk/ocean/zheng/summarization_svcca/out/activations/amazon_reviews/seed1/100_data/top5/epoch191/Movies_and_TV_layer_8_hidden_state.npy'
Traceback (most recent call last):
  File "analysis.py", line 101, in <module>
    SVCCA(args.data_dir1, args.data_dir2, args.svd_dim)
  File "analysis.py", line 15, in SVCCA
    acts1 = np.load(file1)
  File "/disk/ocean/zheng/miniconda3/envs/cdt/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/disk/ocean/zheng/summarization_svcca/out/activations/amazon_reviews/seed1/100_data/top5/epoch201/Movies_and_TV_layer_8_hidden_state.npy'
Traceback (most recent call last):
  File "analysis.py", line 101, in <module>
    SVCCA(args.data_dir1, args.data_dir2, args.svd_dim)
  File "analysis.py", line 15, in SVCCA
    acts1 = np.load(file1)
  File "/disk/ocean/zheng/miniconda3/envs/cdt/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/disk/ocean/zheng/summarization_svcca/out/activations/amazon_reviews/seed1/100_data/top5/epoch111/Movies_and_TV_layer_9_hidden_state.npy'
Traceback (most recent call last):
  File "analysis.py", line 101, in <module>
    SVCCA(args.data_dir1, args.data_dir2, args.svd_dim)
  File "analysis.py", line 15, in SVCCA
    acts1 = np.load(file1)
  File "/disk/ocean/zheng/miniconda3/envs/cdt/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/disk/ocean/zheng/summarization_svcca/out/activations/amazon_reviews/seed1/100_data/top5/epoch121/Movies_and_TV_layer_9_hidden_state.npy'
Traceback (most recent call last):
  File "analysis.py", line 101, in <module>
    SVCCA(args.data_dir1, args.data_dir2, args.svd_dim)
  File "analysis.py", line 15, in SVCCA
    acts1 = np.load(file1)
  File "/disk/ocean/zheng/miniconda3/envs/cdt/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/disk/ocean/zheng/summarization_svcca/out/activations/amazon_reviews/seed1/100_data/top5/epoch131/Movies_and_TV_layer_9_hidden_state.npy'
Traceback (most recent call last):
  File "analysis.py", line 101, in <module>
    SVCCA(args.data_dir1, args.data_dir2, args.svd_dim)
  File "analysis.py", line 15, in SVCCA
    acts1 = np.load(file1)
  File "/disk/ocean/zheng/miniconda3/envs/cdt/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/disk/ocean/zheng/summarization_svcca/out/activations/amazon_reviews/seed1/100_data/top5/epoch141/Movies_and_TV_layer_9_hidden_state.npy'
Traceback (most recent call last):
  File "analysis.py", line 101, in <module>
    SVCCA(args.data_dir1, args.data_dir2, args.svd_dim)
  File "analysis.py", line 15, in SVCCA
    acts1 = np.load(file1)
  File "/disk/ocean/zheng/miniconda3/envs/cdt/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/disk/ocean/zheng/summarization_svcca/out/activations/amazon_reviews/seed1/100_data/top5/epoch151/Movies_and_TV_layer_9_hidden_state.npy'
Traceback (most recent call last):
  File "analysis.py", line 101, in <module>
    SVCCA(args.data_dir1, args.data_dir2, args.svd_dim)
  File "analysis.py", line 15, in SVCCA
    acts1 = np.load(file1)
  File "/disk/ocean/zheng/miniconda3/envs/cdt/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/disk/ocean/zheng/summarization_svcca/out/activations/amazon_reviews/seed1/100_data/top5/epoch161/Movies_and_TV_layer_9_hidden_state.npy'
Traceback (most recent call last):
  File "analysis.py", line 101, in <module>
    SVCCA(args.data_dir1, args.data_dir2, args.svd_dim)
  File "analysis.py", line 15, in SVCCA
    acts1 = np.load(file1)
  File "/disk/ocean/zheng/miniconda3/envs/cdt/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/disk/ocean/zheng/summarization_svcca/out/activations/amazon_reviews/seed1/100_data/top5/epoch171/Movies_and_TV_layer_9_hidden_state.npy'
Traceback (most recent call last):
  File "analysis.py", line 101, in <module>
    SVCCA(args.data_dir1, args.data_dir2, args.svd_dim)
  File "analysis.py", line 15, in SVCCA
    acts1 = np.load(file1)
  File "/disk/ocean/zheng/miniconda3/envs/cdt/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/disk/ocean/zheng/summarization_svcca/out/activations/amazon_reviews/seed1/100_data/top5/epoch191/Movies_and_TV_layer_9_hidden_state.npy'
Traceback (most recent call last):
  File "analysis.py", line 101, in <module>
    SVCCA(args.data_dir1, args.data_dir2, args.svd_dim)
  File "analysis.py", line 16, in SVCCA
    acts2 = np.load(file2)
  File "/disk/ocean/zheng/miniconda3/envs/cdt/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/disk/ocean/zheng/summarization_svcca/out/activations/amazon_reviews/seed1/100_data/Movies_and_TV/epoch201/Movies_and_TV_layer_9_hidden_state.npy'
Traceback (most recent call last):
  File "analysis.py", line 101, in <module>
    SVCCA(args.data_dir1, args.data_dir2, args.svd_dim)
  File "analysis.py", line 15, in SVCCA
    acts1 = np.load(file1)
  File "/disk/ocean/zheng/miniconda3/envs/cdt/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/disk/ocean/zheng/summarization_svcca/out/activations/amazon_reviews/seed1/100_data/top5/epoch101/Movies_and_TV_layer_10_hidden_state.npy'
Traceback (most recent call last):
  File "analysis.py", line 101, in <module>
    SVCCA(args.data_dir1, args.data_dir2, args.svd_dim)
  File "analysis.py", line 15, in SVCCA
    acts1 = np.load(file1)
  File "/disk/ocean/zheng/miniconda3/envs/cdt/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/disk/ocean/zheng/summarization_svcca/out/activations/amazon_reviews/seed1/100_data/top5/epoch111/Movies_and_TV_layer_10_hidden_state.npy'
Traceback (most recent call last):
  File "analysis.py", line 101, in <module>
    SVCCA(args.data_dir1, args.data_dir2, args.svd_dim)
  File "analysis.py", line 15, in SVCCA
    acts1 = np.load(file1)
  File "/disk/ocean/zheng/miniconda3/envs/cdt/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/disk/ocean/zheng/summarization_svcca/out/activations/amazon_reviews/seed1/100_data/top5/epoch121/Movies_and_TV_layer_10_hidden_state.npy'
Traceback (most recent call last):
  File "analysis.py", line 101, in <module>
    SVCCA(args.data_dir1, args.data_dir2, args.svd_dim)
  File "analysis.py", line 15, in SVCCA
    acts1 = np.load(file1)
  File "/disk/ocean/zheng/miniconda3/envs/cdt/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/disk/ocean/zheng/summarization_svcca/out/activations/amazon_reviews/seed1/100_data/top5/epoch131/Movies_and_TV_layer_10_hidden_state.npy'
Traceback (most recent call last):
  File "analysis.py", line 101, in <module>
    SVCCA(args.data_dir1, args.data_dir2, args.svd_dim)
  File "analysis.py", line 15, in SVCCA
    acts1 = np.load(file1)
  File "/disk/ocean/zheng/miniconda3/envs/cdt/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/disk/ocean/zheng/summarization_svcca/out/activations/amazon_reviews/seed1/100_data/top5/epoch141/Movies_and_TV_layer_10_hidden_state.npy'
Traceback (most recent call last):
  File "analysis.py", line 101, in <module>
    SVCCA(args.data_dir1, args.data_dir2, args.svd_dim)
  File "analysis.py", line 16, in SVCCA
    acts2 = np.load(file2)
  File "/disk/ocean/zheng/miniconda3/envs/cdt/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/disk/ocean/zheng/summarization_svcca/out/activations/amazon_reviews/seed1/100_data/Movies_and_TV/epoch151/Movies_and_TV_layer_10_hidden_state.npy'
Traceback (most recent call last):
  File "analysis.py", line 101, in <module>
    SVCCA(args.data_dir1, args.data_dir2, args.svd_dim)
  File "analysis.py", line 15, in SVCCA
    acts1 = np.load(file1)
  File "/disk/ocean/zheng/miniconda3/envs/cdt/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/disk/ocean/zheng/summarization_svcca/out/activations/amazon_reviews/seed1/100_data/top5/epoch161/Movies_and_TV_layer_10_hidden_state.npy'
Traceback (most recent call last):
  File "analysis.py", line 101, in <module>
    SVCCA(args.data_dir1, args.data_dir2, args.svd_dim)
  File "analysis.py", line 16, in SVCCA
    acts2 = np.load(file2)
  File "/disk/ocean/zheng/miniconda3/envs/cdt/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/disk/ocean/zheng/summarization_svcca/out/activations/amazon_reviews/seed1/100_data/Movies_and_TV/epoch171/Movies_and_TV_layer_10_hidden_state.npy'
Traceback (most recent call last):
  File "analysis.py", line 101, in <module>
    SVCCA(args.data_dir1, args.data_dir2, args.svd_dim)
  File "analysis.py", line 15, in SVCCA
    acts1 = np.load(file1)
  File "/disk/ocean/zheng/miniconda3/envs/cdt/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/disk/ocean/zheng/summarization_svcca/out/activations/amazon_reviews/seed1/100_data/top5/epoch181/Movies_and_TV_layer_10_hidden_state.npy'
Traceback (most recent call last):
  File "analysis.py", line 101, in <module>
    SVCCA(args.data_dir1, args.data_dir2, args.svd_dim)
  File "analysis.py", line 15, in SVCCA
    acts1 = np.load(file1)
  File "/disk/ocean/zheng/miniconda3/envs/cdt/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/disk/ocean/zheng/summarization_svcca/out/activations/amazon_reviews/seed1/100_data/top5/epoch191/Movies_and_TV_layer_10_hidden_state.npy'
Traceback (most recent call last):
  File "analysis.py", line 101, in <module>
    SVCCA(args.data_dir1, args.data_dir2, args.svd_dim)
  File "analysis.py", line 15, in SVCCA
    acts1 = np.load(file1)
  File "/disk/ocean/zheng/miniconda3/envs/cdt/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/disk/ocean/zheng/summarization_svcca/out/activations/amazon_reviews/seed1/100_data/top5/epoch201/Movies_and_TV_layer_10_hidden_state.npy'
Traceback (most recent call last):
  File "analysis.py", line 101, in <module>
    SVCCA(args.data_dir1, args.data_dir2, args.svd_dim)
  File "analysis.py", line 15, in SVCCA
    acts1 = np.load(file1)
  File "/disk/ocean/zheng/miniconda3/envs/cdt/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/disk/ocean/zheng/summarization_svcca/out/activations/amazon_reviews/seed1/100_data/top5/epoch101/Movies_and_TV_layer_11_hidden_state.npy'
Traceback (most recent call last):
  File "analysis.py", line 101, in <module>
    SVCCA(args.data_dir1, args.data_dir2, args.svd_dim)
  File "analysis.py", line 15, in SVCCA
    acts1 = np.load(file1)
  File "/disk/ocean/zheng/miniconda3/envs/cdt/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/disk/ocean/zheng/summarization_svcca/out/activations/amazon_reviews/seed1/100_data/top5/epoch111/Movies_and_TV_layer_11_hidden_state.npy'
Traceback (most recent call last):
  File "analysis.py", line 101, in <module>
    SVCCA(args.data_dir1, args.data_dir2, args.svd_dim)
  File "analysis.py", line 16, in SVCCA
    acts2 = np.load(file2)
  File "/disk/ocean/zheng/miniconda3/envs/cdt/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/disk/ocean/zheng/summarization_svcca/out/activations/amazon_reviews/seed1/100_data/Movies_and_TV/epoch121/Movies_and_TV_layer_11_hidden_state.npy'
Traceback (most recent call last):
  File "analysis.py", line 101, in <module>
    SVCCA(args.data_dir1, args.data_dir2, args.svd_dim)
  File "analysis.py", line 15, in SVCCA
    acts1 = np.load(file1)
  File "/disk/ocean/zheng/miniconda3/envs/cdt/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/disk/ocean/zheng/summarization_svcca/out/activations/amazon_reviews/seed1/100_data/top5/epoch131/Movies_and_TV_layer_11_hidden_state.npy'
Traceback (most recent call last):
  File "analysis.py", line 101, in <module>
    SVCCA(args.data_dir1, args.data_dir2, args.svd_dim)
  File "analysis.py", line 16, in SVCCA
    acts2 = np.load(file2)
  File "/disk/ocean/zheng/miniconda3/envs/cdt/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/disk/ocean/zheng/summarization_svcca/out/activations/amazon_reviews/seed1/100_data/Movies_and_TV/epoch141/Movies_and_TV_layer_11_hidden_state.npy'
Traceback (most recent call last):
  File "analysis.py", line 101, in <module>
    SVCCA(args.data_dir1, args.data_dir2, args.svd_dim)
  File "analysis.py", line 16, in SVCCA
    acts2 = np.load(file2)
  File "/disk/ocean/zheng/miniconda3/envs/cdt/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/disk/ocean/zheng/summarization_svcca/out/activations/amazon_reviews/seed1/100_data/Movies_and_TV/epoch151/Movies_and_TV_layer_11_hidden_state.npy'
Traceback (most recent call last):
  File "analysis.py", line 101, in <module>
    SVCCA(args.data_dir1, args.data_dir2, args.svd_dim)
  File "analysis.py", line 15, in SVCCA
    acts1 = np.load(file1)
  File "/disk/ocean/zheng/miniconda3/envs/cdt/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/disk/ocean/zheng/summarization_svcca/out/activations/amazon_reviews/seed1/100_data/top5/epoch161/Movies_and_TV_layer_11_hidden_state.npy'
Traceback (most recent call last):
  File "analysis.py", line 101, in <module>
    SVCCA(args.data_dir1, args.data_dir2, args.svd_dim)
  File "analysis.py", line 16, in SVCCA
    acts2 = np.load(file2)
  File "/disk/ocean/zheng/miniconda3/envs/cdt/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/disk/ocean/zheng/summarization_svcca/out/activations/amazon_reviews/seed1/100_data/Movies_and_TV/epoch171/Movies_and_TV_layer_11_hidden_state.npy'
Traceback (most recent call last):
  File "analysis.py", line 101, in <module>
    SVCCA(args.data_dir1, args.data_dir2, args.svd_dim)
  File "analysis.py", line 15, in SVCCA
    acts1 = np.load(file1)
  File "/disk/ocean/zheng/miniconda3/envs/cdt/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/disk/ocean/zheng/summarization_svcca/out/activations/amazon_reviews/seed1/100_data/top5/epoch181/Movies_and_TV_layer_11_hidden_state.npy'
Traceback (most recent call last):
  File "analysis.py", line 101, in <module>
    SVCCA(args.data_dir1, args.data_dir2, args.svd_dim)
  File "analysis.py", line 15, in SVCCA
    acts1 = np.load(file1)
  File "/disk/ocean/zheng/miniconda3/envs/cdt/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/disk/ocean/zheng/summarization_svcca/out/activations/amazon_reviews/seed1/100_data/top5/epoch191/Movies_and_TV_layer_11_hidden_state.npy'
Traceback (most recent call last):
  File "analysis.py", line 101, in <module>
    SVCCA(args.data_dir1, args.data_dir2, args.svd_dim)
  File "analysis.py", line 15, in SVCCA
    acts1 = np.load(file1)
  File "/disk/ocean/zheng/miniconda3/envs/cdt/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/disk/ocean/zheng/summarization_svcca/out/activations/amazon_reviews/seed1/100_data/top5/epoch201/Movies_and_TV_layer_11_hidden_state.npy'
Traceback (most recent call last):
  File "analysis.py", line 101, in <module>
    SVCCA(args.data_dir1, args.data_dir2, args.svd_dim)
  File "analysis.py", line 15, in SVCCA
    acts1 = np.load(file1)
  File "/disk/ocean/zheng/miniconda3/envs/cdt/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/disk/ocean/zheng/summarization_svcca/out/activations/amazon_reviews/seed1/100_data/top5/epoch101/Movies_and_TV_layer_12_hidden_state.npy'
Traceback (most recent call last):
  File "analysis.py", line 101, in <module>
    SVCCA(args.data_dir1, args.data_dir2, args.svd_dim)
  File "analysis.py", line 15, in SVCCA
    acts1 = np.load(file1)
  File "/disk/ocean/zheng/miniconda3/envs/cdt/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/disk/ocean/zheng/summarization_svcca/out/activations/amazon_reviews/seed1/100_data/top5/epoch111/Movies_and_TV_layer_12_hidden_state.npy'
Traceback (most recent call last):
  File "analysis.py", line 101, in <module>
    SVCCA(args.data_dir1, args.data_dir2, args.svd_dim)
  File "analysis.py", line 16, in SVCCA
    acts2 = np.load(file2)
  File "/disk/ocean/zheng/miniconda3/envs/cdt/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/disk/ocean/zheng/summarization_svcca/out/activations/amazon_reviews/seed1/100_data/Movies_and_TV/epoch121/Movies_and_TV_layer_12_hidden_state.npy'
Traceback (most recent call last):
  File "analysis.py", line 101, in <module>
    SVCCA(args.data_dir1, args.data_dir2, args.svd_dim)
  File "analysis.py", line 15, in SVCCA
    acts1 = np.load(file1)
  File "/disk/ocean/zheng/miniconda3/envs/cdt/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/disk/ocean/zheng/summarization_svcca/out/activations/amazon_reviews/seed1/100_data/top5/epoch131/Movies_and_TV_layer_12_hidden_state.npy'
Traceback (most recent call last):
  File "analysis.py", line 101, in <module>
    SVCCA(args.data_dir1, args.data_dir2, args.svd_dim)
  File "analysis.py", line 15, in SVCCA
    acts1 = np.load(file1)
  File "/disk/ocean/zheng/miniconda3/envs/cdt/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/disk/ocean/zheng/summarization_svcca/out/activations/amazon_reviews/seed1/100_data/top5/epoch141/Movies_and_TV_layer_12_hidden_state.npy'
Traceback (most recent call last):
  File "analysis.py", line 101, in <module>
    SVCCA(args.data_dir1, args.data_dir2, args.svd_dim)
  File "analysis.py", line 16, in SVCCA
    acts2 = np.load(file2)
  File "/disk/ocean/zheng/miniconda3/envs/cdt/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/disk/ocean/zheng/summarization_svcca/out/activations/amazon_reviews/seed1/100_data/Movies_and_TV/epoch151/Movies_and_TV_layer_12_hidden_state.npy'
Traceback (most recent call last):
  File "analysis.py", line 101, in <module>
    SVCCA(args.data_dir1, args.data_dir2, args.svd_dim)
  File "analysis.py", line 15, in SVCCA
    acts1 = np.load(file1)
  File "/disk/ocean/zheng/miniconda3/envs/cdt/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/disk/ocean/zheng/summarization_svcca/out/activations/amazon_reviews/seed1/100_data/top5/epoch161/Movies_and_TV_layer_12_hidden_state.npy'
Traceback (most recent call last):
  File "analysis.py", line 101, in <module>
    SVCCA(args.data_dir1, args.data_dir2, args.svd_dim)
  File "analysis.py", line 15, in SVCCA
    acts1 = np.load(file1)
  File "/disk/ocean/zheng/miniconda3/envs/cdt/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/disk/ocean/zheng/summarization_svcca/out/activations/amazon_reviews/seed1/100_data/top5/epoch171/Movies_and_TV_layer_12_hidden_state.npy'
Traceback (most recent call last):
  File "analysis.py", line 101, in <module>
    SVCCA(args.data_dir1, args.data_dir2, args.svd_dim)
  File "analysis.py", line 15, in SVCCA
    acts1 = np.load(file1)
  File "/disk/ocean/zheng/miniconda3/envs/cdt/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/disk/ocean/zheng/summarization_svcca/out/activations/amazon_reviews/seed1/100_data/top5/epoch181/Movies_and_TV_layer_12_hidden_state.npy'
Traceback (most recent call last):
  File "analysis.py", line 101, in <module>
    SVCCA(args.data_dir1, args.data_dir2, args.svd_dim)
  File "analysis.py", line 16, in SVCCA
    acts2 = np.load(file2)
  File "/disk/ocean/zheng/miniconda3/envs/cdt/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/disk/ocean/zheng/summarization_svcca/out/activations/amazon_reviews/seed1/100_data/Movies_and_TV/epoch191/Movies_and_TV_layer_12_hidden_state.npy'
Traceback (most recent call last):
  File "analysis.py", line 101, in <module>
    SVCCA(args.data_dir1, args.data_dir2, args.svd_dim)
  File "analysis.py", line 15, in SVCCA
    acts1 = np.load(file1)
  File "/disk/ocean/zheng/miniconda3/envs/cdt/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/disk/ocean/zheng/summarization_svcca/out/activations/amazon_reviews/seed1/100_data/top5/epoch201/Movies_and_TV_layer_12_hidden_state.npy'
